#!/usr/bin/env python3
"""Resolve SVG reuse decisions by matching manifest hashes against existing assets."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
from pathlib import Path
from typing import Any

MANIFEST_SUFFIX = "-svg-manifest.json"
REPORT_SUFFIX = "-svg-reuse-report.json"
DEFAULT_FIGMA_DIR = Path("spec/figma")
TAG_GAP_PATTERN = re.compile(r">\s+<")
MULTI_BLANK_LINE_PATTERN = re.compile(r"\n{2,}")
SLUG_PATTERN = re.compile(r"[^a-z0-9]+")
COMMON_ASSET_DIRS = (
    "assets",
    "lib/assets",
    "lib/components/assets",
    "lib/components/icons",
    "src/assets",
    "src/icons",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Resolve SVG asset reuse decisions from a hash manifest")
    parser.add_argument(
        "--svg-manifest",
        help="Path to *-svg-manifest.json generated by figma-context-extractor (defaults to latest under spec/figma)",
    )
    parser.add_argument(
        "--existing-svg-dir",
        action="append",
        default=[],
        help="Repeatable path to existing SVG asset directories to scan",
    )
    parser.add_argument(
        "--new-svg-dir",
        help="Optional target directory to copy unmatched SVG cache files",
    )
    parser.add_argument(
        "--report-path",
        help="Optional explicit output path for reuse report JSON",
    )
    parser.add_argument(
        "--overwrite-new",
        action="store_true",
        help="Overwrite generated SVG files in --new-svg-dir when file exists",
    )
    return parser.parse_args()


def normalize_svg_xml(svg_xml: str) -> str:
    normalized = svg_xml.replace("\r\n", "\n").replace("\r", "\n").strip()
    normalized = TAG_GAP_PATTERN.sub("><", normalized)
    normalized = MULTI_BLANK_LINE_PATTERN.sub("\n", normalized)
    return normalized


def safe_str(value: Any) -> str:
    return value if isinstance(value, str) else ""


def display_path(path: Path, base_dir: Path) -> str:
    try:
        return path.resolve().relative_to(base_dir.resolve()).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def resolve_candidate_dirs(explicit_dirs: list[str], base_dir: Path) -> list[Path]:
    candidates: list[Path] = []
    if explicit_dirs:
        for item in explicit_dirs:
            path = Path(item)
            if not path.is_absolute():
                path = base_dir / path
            if path.exists() and path.is_dir():
                candidates.append(path.resolve())
    else:
        for item in COMMON_ASSET_DIRS:
            path = (base_dir / item).resolve()
            if path.exists() and path.is_dir():
                candidates.append(path)

    seen: set[Path] = set()
    out: list[Path] = []
    for path in candidates:
        if path in seen:
            continue
        seen.add(path)
        out.append(path)
    return out


def sha256_svg_file(path: Path) -> str | None:
    try:
        content = path.read_text(encoding="utf-8-sig")
    except OSError:
        return None

    normalized = normalize_svg_xml(content)
    if not normalized:
        return None
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def build_existing_hash_index(scan_dirs: list[Path]) -> dict[str, list[Path]]:
    index: dict[str, list[Path]] = {}
    for root in scan_dirs:
        for svg_file in root.rglob("*.svg"):
            if not svg_file.is_file():
                continue
            digest = sha256_svg_file(svg_file)
            if not digest:
                continue
            index.setdefault(digest, []).append(svg_file.resolve())

    for digest in index:
        index[digest] = sorted(index[digest], key=lambda item: item.as_posix())
    return index


def infer_report_path(manifest_path: Path) -> Path:
    file_name = manifest_path.name
    stem = file_name[: -len(MANIFEST_SUFFIX)] if file_name.endswith(MANIFEST_SUFFIX) else manifest_path.stem
    return manifest_path.with_name(f"{stem}{REPORT_SUFFIX}")


def find_latest_manifest(base_dir: Path) -> Path | None:
    root = (base_dir / DEFAULT_FIGMA_DIR).resolve()
    if not root.exists() or not root.is_dir():
        return None

    manifests = [path for path in root.glob(f"*{MANIFEST_SUFFIX}") if path.is_file()]
    if not manifests:
        return None

    manifests.sort(key=lambda item: item.stat().st_mtime, reverse=True)
    return manifests[0]


def load_manifest(manifest_path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
    except OSError as exc:
        raise RuntimeError(f"Unable to read manifest file: {manifest_path}") from exc
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"Manifest parse failed: {manifest_path}") from exc

    if not isinstance(payload, dict):
        raise RuntimeError("Manifest root must be an object.")
    return payload


def load_assets(payload: dict[str, Any]) -> list[dict[str, Any]]:
    raw_assets = payload.get("assets")
    if not isinstance(raw_assets, list):
        return []
    return [item for item in raw_assets if isinstance(item, dict)]


def resolve_cached_svg_path(cached_svg_path: str, manifest_path: Path, base_dir: Path) -> Path | None:
    if not cached_svg_path:
        return None

    raw = Path(cached_svg_path)
    candidates = []
    if raw.is_absolute():
        candidates.append(raw)
    else:
        candidates.append((base_dir / raw).resolve())
        candidates.append((manifest_path.parent / raw).resolve())
        candidates.append(raw.resolve())

    for candidate in candidates:
        if candidate.exists() and candidate.is_file():
            return candidate
    return None


def slugify(value: str, fallback: str = "icon") -> str:
    lowered = value.strip().lower()
    normalized = SLUG_PATTERN.sub("-", lowered).strip("-")
    return normalized or fallback


def choose_target_file_name(name: str, svg_hash: str, target_dir: Path) -> Path:
    base = slugify(name or "icon")
    short_hash = svg_hash[:8] if svg_hash else "unknown"
    candidate = target_dir / f"{base}-{short_hash}.svg"
    if not candidate.exists():
        return candidate

    index = 2
    while True:
        alt = target_dir / f"{base}-{short_hash}-{index}.svg"
        if not alt.exists():
            return alt
        index += 1


def maybe_copy_new_svg(
    item: dict[str, Any],
    manifest_path: Path,
    base_dir: Path,
    new_svg_dir: Path | None,
    overwrite_new: bool,
) -> tuple[str | None, str | None]:
    if new_svg_dir is None:
        return None, "new_svg_dir_not_set"

    cached_path = resolve_cached_svg_path(safe_str(item.get("cached_svg_path")), manifest_path, base_dir)
    if cached_path is None:
        return None, "cached_svg_missing"

    svg_hash = safe_str(item.get("svg_hash"))
    name = safe_str(item.get("name"))
    target_file = choose_target_file_name(name, svg_hash, new_svg_dir)

    if target_file.exists() and not overwrite_new:
        return display_path(target_file, base_dir), "target_exists"

    try:
        shutil.copyfile(cached_path, target_file)
    except OSError:
        return None, "copy_failed"
    return display_path(target_file, base_dir), None


def build_reuse_report(
    manifest_path: Path,
    payload: dict[str, Any],
    existing_index: dict[str, list[Path]],
    scan_dirs: list[Path],
    new_svg_dir: Path | None,
    overwrite_new: bool,
    base_dir: Path,
) -> dict[str, Any]:
    assets = load_assets(payload)
    decisions: list[dict[str, Any]] = []
    reused = 0
    added = 0
    unresolved = 0

    for item in assets:
        node_id = safe_str(item.get("node_id"))
        svg_hash = safe_str(item.get("svg_hash"))
        existing_matches = existing_index.get(svg_hash, []) if svg_hash else []

        decision = "reuse" if existing_matches else "new"
        reused_path = display_path(existing_matches[0], base_dir) if existing_matches else ""
        created_path = ""
        create_error = ""

        if decision == "reuse":
            reused += 1
        else:
            created_path, create_error = maybe_copy_new_svg(item, manifest_path, base_dir, new_svg_dir, overwrite_new)
            if created_path:
                added += 1
            else:
                unresolved += 1

        decisions.append(
            {
                "node_id": node_id,
                "name": safe_str(item.get("name")),
                "type": safe_str(item.get("type")),
                "svg_hash": svg_hash,
                "decision": decision,
                "reuse_asset_path": reused_path,
                "new_asset_path": created_path or "",
                "new_asset_error": create_error or "",
                "cached_svg_path": safe_str(item.get("cached_svg_path")),
            }
        )

    return {
        "source_manifest": display_path(manifest_path, base_dir),
        "scan_dirs": [display_path(path, base_dir) for path in scan_dirs],
        "new_svg_dir": display_path(new_svg_dir, base_dir) if new_svg_dir else "",
        "asset_count": len(assets),
        "reuse_count": reused,
        "new_count": len(assets) - reused,
        "copied_new_count": added,
        "unresolved_new_count": unresolved,
        "decisions": decisions,
    }


def main() -> int:
    args = parse_args()
    base_dir = Path.cwd()
    manifest_path = Path(args.svg_manifest) if args.svg_manifest else find_latest_manifest(base_dir)
    if manifest_path is None:
        print(
            "Error: SVG manifest not found. Pass --svg-manifest or place *-svg-manifest.json under spec/figma.",
            file=sys.stderr,
        )
        return 2

    if not manifest_path.exists():
        print(f"Error: SVG manifest file not found: {manifest_path}", file=sys.stderr)
        return 2

    try:
        payload = load_manifest(manifest_path)
    except RuntimeError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    scan_dirs = resolve_candidate_dirs(args.existing_svg_dir, base_dir)
    existing_index = build_existing_hash_index(scan_dirs)

    new_svg_dir = Path(args.new_svg_dir).resolve() if args.new_svg_dir else None
    if new_svg_dir:
        try:
            new_svg_dir.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            print(f"Error: unable to create --new-svg-dir: {exc}", file=sys.stderr)
            return 1

    report_path = Path(args.report_path) if args.report_path else infer_report_path(manifest_path)
    try:
        report_path.parent.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        print(f"Error: unable to create report directory: {exc}", file=sys.stderr)
        return 1

    report = build_reuse_report(
        manifest_path=manifest_path,
        payload=payload,
        existing_index=existing_index,
        scan_dirs=scan_dirs,
        new_svg_dir=new_svg_dir,
        overwrite_new=args.overwrite_new,
        base_dir=base_dir,
    )

    try:
        report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    except OSError as exc:
        print(f"Error: unable to write report file: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote SVG reuse report: {report_path}")
    print(
        "SVG reuse decisions: total={total}, reuse={reuse}, new={new}, copied_new={copied}, unresolved_new={unresolved}".format(
            total=report["asset_count"],
            reuse=report["reuse_count"],
            new=report["new_count"],
            copied=report["copied_new_count"],
            unresolved=report["unresolved_new_count"],
        )
    )
    if not report["scan_dirs"]:
        print("Warning: no existing SVG directories were scanned.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
